FROM nginx
COPY /home/eugene/Documents/ELK/nginx/www/html/index.html /usr/share/nginx/html
COPY /home/eugene/Documents/ELK/nginx/www/html/index.html /var/www/html
CMD [nginx-debug, '-g', 'daemon off;']
#COPY /home/eugene/Documents/ELK/nginx/conf/nginx.conf /etc/nginx/nginx.conf
